apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebuilder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rebuilder
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rebuilder
    spec:
      containers:
        - image: quay.io/jduimovich0/rebuilder:2023-03-20-164726
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          name: rebuilder-image
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rebuilder
  name: rebuilder
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: rebuilder
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rebuilder
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rebuilder
    weight: 100
